name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@095e2104b04f50719b32a2a9c432b2570093456c # v1.44.0
        with:
          audience: ""

      - name: Setup niks3 cache
        uses: spotdemo4/niks3-action@main # zizmor: ignore[unpinned-uses]
        with:
          server-url: https://niks3.trev.zip
          auth-token: ${{ secrets.NIKS3_TOKEN }}
          inputs-from: .

      - name: Check flake
        run: nix flake check

  oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@095e2104b04f50719b32a2a9c432b2570093456c # v1.44.0
        with:
          audience: ""

      - name: Setup niks3 cache
        uses: spotdemo4/niks3-action@main # zizmor: ignore[unpinned-uses]
        with:
          audience: https://niks3.trev.zip

      - name: Check flake
        run: nix flake check
