name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@8cfbe9e5d4eef03c557a70763c90af7ff4aafe67 # v1.46.0
        with:
          fetch_depth: 0
          shell: release

      - name: Run flake-release
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
